#!/bin/sh

#------------------------------------------------------------------------------
# 1D Infiltration with Saturation Overshoot
#
# This case demonstrates the formation of saturation overshoot during 1D
# vertical infiltration into an initially dry porous medium. The simulation
# reproduces experimental conditions from DiCarlo (2004) showing non-monotonic
# saturation profiles.
#------------------------------------------------------------------------------

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clean previous results and restore initial fields
rm -rf 0 0.* [1-9]* log* processor* postProcessing
cp -r 0_orig 0

runApplication blockMesh
runApplication onePhaseMixtureFoam
