#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -r 0.* [1-9]*
cp -r 0_orig/* 0/
rm -r  log* proc*

runApplication blockMesh
runApplication onePhaseMixtureFoam 

