#!/bin/sh

#------------------------------------------------------------------------------
# 2D Gravity Fingering in Heterogeneous Porous Media
#
# This case simulates 2D gravity-driven fingering instabilities during
# infiltration into heterogeneous, dry porous media with a randomly initialized
# permeability field. The simulation shows finger formation, growth, and
# lateral competition driven by the interplay between second viscosity effects
# and permeability heterogeneity.
#------------------------------------------------------------------------------

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clean previous results and restore initial fields
rm -rf 0 0.* [1-9]* log* processor* postProcessing
cp -r 0_orig 0

runApplication blockMesh

# Serial run
runApplication onePhaseMixtureFoam

# Parallel run (alternative to the serial run above)
#runApplication decomposePar
#runParallel onePhaseMixtureFoam
#runApplication reconstructPar
